version: 0.5.4.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
before_build:
- cmd: dotnet restore src
build:
  verbosity: minimal
only_commits:
  files:
    - src/